const stockObj = {
    BIOPHARM: {
    MATINAS:'MTNB',
    MANNKIND:'MNKD',
    'BIO-KEY':'BKYI',
    SCYNEXIS:'SCYX',
    ORGANOVO:'ONVO',
    IBIO:'IBIO',
    BIOCEPT:'BIOC',
    DYNATRONICS:'DYNT',
    ZOMEDICA:'ZOM',
    CLEANSPARK:'CLSK'
    },
    TECH: {
    INPIXON:'INPX',
    SUPERCONDUCTOR:'SCON',
    SPHERE:'ANY',
    TARONIS:'TRNX',
    NOKIA:'NOK',
    FUELCELL:'FCEL',
    CYNERGISTEK:'CTEK',
    MITCHAM:'MIND',
    TESLA:'TSLA',
    SPI:'SPI',
    VERB:'VERB',
    '3M':'MMM'
    },
    HEALTHCARE: {
    AGILENT:'A',
    OPGEN:'OPGN',
    NEURONETICS:'STIM',
    EXAGEN:'XGN',
    T2BIOSYSTEMS:'TTOO',
    BIONANO:'BNGO',
    PERKINELMER:'PKI',
    HTGMOLECULAR:'HTGM',
    PRECIPIO:'PRPO',
    CHECKCAP:'CHEK'
    },
    INDUSTRIAL: {
    BIOHITECH:'BHTG',
    CEMTREX:'CETX',
    MICT:'MICT',
    VERTEX:'VTNR',
    AIRINDUSTRIES:'AIRI',
    TOUGHBUILT:'TBLT',
    AQUAMETALS:'AQMS',
    CHARAHSOLUTIONS:'CHRA',
    NUVERRA:'NES',
    FUELCELL:'FCEL',
    LIGHTPATH:'LPTH'
    },
    EDUCATION: {
    ZOVIO:'ZVO',
    CISCO:'CSCO',
    GOOGLE:'GOOGL',
    ARCO:'ARCE',
    PERDOCEO:'PRDO',
    INSTRUCTURE:'INST',
    CHEGG:'CHGG',
    NEWORIENTALEDUCATION:'EDU',
    K12:'LRN',
    BRIGHTHORIZONS:'BFAM'
    }
}